import { useTranslation } from 'react-i18next';

import { EntitiesImages } from '@/src/app/assets/images/entities';

export const PartnersContent = () => {
  const { i18n } = useTranslation();

  return i18n.language === 'ar'
    ? [
        {
          id: '0',
          name: 'وزارة الصناعة والثروة المعدنية',
          info: 'وزارة الصناعة والثروة المعدنية هي هيئة حكومية سعودية مسؤولة عن عمليات الصناعة والموارد المعدنية. تم إنشاء الوزارة في 30 أغسطس 2019 بعد فصل وزارة الطاقة والصناعة والثروة المعدنية في وزارة الطاقة ووزارة الصناعة والثروة المعدنية.تهدف الوزارة إلى تنويع مصادر الدخل الوطني.',
          imageSrc: EntitiesImages.Entity4,
          modalLogo: EntitiesImages.E4,
          websiteUrl: 'https://mim.gov.sa/',
        },
        {
          id: '1',
          name: 'وزارة الطاقة',
          info: 'تعمل وزارة الطاقة على التطوير المستدام لصناعة البترول والغاز المتكاملة في جميع مراحلها لتحقيق أعلى قيمة مضافة للاقتصاد الوطني و اكتشاف واستثمار موارد المملكة من البترول والغاز وتحقيق أعلى مردود منها.',
          imageSrc: EntitiesImages.Entity35,
          modalLogo: EntitiesImages.E35,
          websiteUrl: 'https://www.moenergy.gov.sa/ar/Pages/default.aspx',
        },
        {
          id: '2',
          name: 'وزارة النقل',
          info: 'تعمل وزارة النقل على دراسة وتصميم وتنفيذ أعمال الطرق وصيانتها بكفاءة، كما تشارك الوزارة في تنسيق اعمال منظومة النقل حيث تلعب دور الجهة المشرعة لجميع أعمال التخطيط والتنفيذ اليومية لخدمات النقل البري والبحري والجوي داخل المملكة، وتحرص على ربط المملكة بالعالم كمركز لوجستي دولي وحلقة وصل وصل للقارات الثلاث. كما تقدم خدمات فعالة لكافة المستفيدين في المملكة، استناداً إلى رؤية تهدف لتطوير قطاع النقل في المملكة وتحقق تناغمًا وتكاملًا حقيقيًا بين كافة قطاعات النقل البرية والبحرية والجوية. كل ذلك ضمن أطر ومنهجية واضحة رسمت معالمها رؤية المملكة 2030، مما سوف يسهم في تعزيز التنمية الاقتصادية والقدرة التنافسية للمملكة على المستوى الدولي.',
          imageSrc: EntitiesImages.Entity13,
          modalLogo: EntitiesImages.E13,
          websiteUrl: 'https://www.mot.gov.sa/en/Pages/default.aspx',
        },
        {
          id: '3',
          name: 'صندوق التنمية الصناعية السعودي',
          info: 'انطلق الصندوق الصناعي ليكون له دوره الفاعل في تعزيز فرص الاستثمار الصناعي، وتطوير الصناعة المحلية ورفع مستوى أدائها، من خلال المساهمة في تشكيل القطاعات الصناعية، وتطوير المؤسسات التنافسية، ودعم المبادرات الاستراتيجية.',
          imageSrc: EntitiesImages.Entity1,
          modalLogo: EntitiesImages.E1,
          websiteUrl: 'https://www.sidf.gov.sa/ar/Pages/Home.aspx',
        },
        {
          id: '4',
          name: 'وزارة الاقتصاد والتخطيط',
          info: 'هي الوزارة المسؤولة عن الشؤون الاقتصادية في المملكة العربية السعودية مع وضع خطط تنموية تتوافق مع رؤية المملكة.',
          imageSrc: EntitiesImages.Entity7,
          modalLogo: EntitiesImages.E7,
          websiteUrl: 'https://www.mep.gov.sa/en',
        },
        {
          id: '5',
          name: 'هيئة المساحة الجيولوجية السعودية',
          info: 'تهدف الهيئة إلى أن تكون مؤسسة رائدة في كافة مجالات علوم الأرض، كما تهدف إلى خدمة المجتمع وجميع المهتمين لخلق بيئة نموذجية، وتسخير التقنية المتطورة والحوافز المتاحة لتعزيز القدرات وتحقيق الأهداف لتوفير حياة أفضل لمجتمعنا.',
          imageSrc: EntitiesImages.Entity6,
          modalLogo: EntitiesImages.E6,
          websiteUrl: 'https://sgs.org.sa/en',
        },
        {
          id: '6',
          name: 'الهيئة السعودية للمواصفات والمقاييس والجودة',
          info: 'تسعى الهيئة السعودية للمواصفات والمقاييس والجودة إلى تقديم أفضل الخدمات للمستفيدين والحفاظ على صحة وسلامة المستهلك، والعمل على تطوير وتحديث المواصفات القياسية السعودية واللوائح الفنية بشكل مستمر لحماية أسواقنا الوطنية من السلع المقلدة والرديئة والمغشوشة ودعم الاقتصاد الوطني.',
          imageSrc: EntitiesImages.Entity8,
          modalLogo: EntitiesImages.E8,
          websiteUrl: 'https://www.saso.gov.sa/ar/pages/default.aspx',
        },
        {
          id: '7',
          name: 'هيئة الزكاة والضريبة والجمارك',
          info: 'الهيئة المعنية بالمساهمة في تحفيز الاقتصاد وتمكين المملكة لتكون مركزاً لوجستياً عالمياً عبر: تيسير التجارة، تحقيق الإيرادات، الاهتمام بالعميل، حماية الوطن والمجتمع بكفاءة وفعالية',
          imageSrc: EntitiesImages.Entity19,
          modalLogo: EntitiesImages.E19,
          websiteUrl: 'https://www.customs.gov.sa/',
        },
        {
          id: '8',
          name: 'الهيئة العامة للغذاء والدواء',
          info: 'الهيئة المعنية بتنظيم ومراقبة الغذاء والدواء والأجهزة الطبية والتشخيصية ووضع المواصفات القياسية الإلزامية لها، المستوردة منها ومحلية الصنع، إضافة إلى فحصها في المختبرات وتوعية المستهلك.',
          imageSrc: EntitiesImages.Entity29,
          modalLogo: EntitiesImages.E29,
          websiteUrl: 'https://www.sfda.gov.sa/',
        },
        {
          id: '9',
          name: 'منشآت',
          info: 'أنشئت الهيئة العامة للمنشآت الصغيرة والمتوسطة "منشآت" عام 2016، وتتلخص أهدافها بتنظيم قطاع المنشآت الصغيرة والمتوسطة في المملكة ودعمه وتنميته ورعايته وفقاً لأفضل الممارسات العالمية، لرفع إنتاجية هذه المنشآت وزيادة مساهمتها في الناتج المحلي الإجمالي من 20% إلى 35% بحلول عام 2030م',
          imageSrc: EntitiesImages.Entity20,
          modalLogo: EntitiesImages.E20,
          websiteUrl: 'https://www.monshaat.gov.sa/en',
        },
        {
          id: '10',
          name: 'وزارة البيئة والمياه والزراعة',
          info: 'تسعى الوزارة للتميز في تطوير وتطبيق السياسات الشاملة والاستراتيجيات الفعالة والارتقاء بالخدمات بمشاركة القطاع الخاص والجهات ذات العلاقة لازدهار واستدامة البيئة والمياه والزراعة.',
          imageSrc: EntitiesImages.Entity36,
          modalLogo: EntitiesImages.E36,
          websiteUrl: 'https://www.mewa.gov.sa/ar/Pages/default.aspx',
        },
        {
          id: '11',
          name: 'وزارة الشؤون البلدية والقروية',
          info: 'هي الوزارة المسؤولة عن التخطيط العمراني لمدن المملكة وما ينتج عن ذلك من توفير التجهيزات الأساسية للطرق وتجميل المدن وتطوير المناطق البلدية والقروية، إضافةً إلى الخدمات اللازمة للحفاظ على نظافة وصحة البيئة بالمملكة.',
          imageSrc: EntitiesImages.Entity16,
          modalLogo: EntitiesImages.E16,
          websiteUrl: 'https://momrah.gov.sa/ar',
        },
        {
          id: '12',
          name: 'وزارة الصحة',
          info: 'إن وزارة الصحة ملتزمة بأداء الرسالة التي تشرفت بحملها منذ قيامها، والتي تقوم على توفير الرعاية الصحية بجميع مستوياتها، وتعزيز الصحة العامة، والوقاية من الأمراض، ووضع القوانين واللوائح المنظمة للقطاع الصحي العام والخاص، ومراقبة أدائه، مع الاهتمام بالجانب البحثي والتدريب الأكاديمي ومجالات الاستثمار الصحي.',
          imageSrc: EntitiesImages.Entity9,
          modalLogo: EntitiesImages.E9,
          websiteUrl: 'https://www.moh.gov.sa/en/Pages/default.aspx',
        },
        {
          id: '13',
          name: 'وزارة الدفاع',
          info: 'مؤسسة حديثة تمتلك قوات عسكرية محترفة ومشتركة تحمي أمن الـــوطن ومصالحه من التهديد الخارجي وتقـــود التحالفات وتشارك بها بجدارة واقتــــدار',
          imageSrc: EntitiesImages.Entity43,
          modalLogo: EntitiesImages.E43,
          websiteUrl: 'https://mod.gov.sa/en/pages/default.aspx',
        },
        {
          id: '14',
          name: 'وزارة الاتصالات وتقنية المعلومات',
          info: 'تهدف الوزارة إلى تطوير قدرات المملكة الرقمية في مجال الاتصالات وتقنية المعلومات، واستثمارها بطريقة مُثلى في نمو مشاريعها المستقبلية، بما يحقق رؤية المملكة 2030، وخدمة الأفراد والمجتمعات، ومواكبة المتطلبات الوطنية والتطورات العالمية، إضافةً إلى استقطاب وجذب المزيد من الاستثمارات التقنية الأجنبية، الأمر الذي يرسم خارطة طريق لمستقبل المملكة في الابتكار والاقتصاد الرقمي.',
          imageSrc: EntitiesImages.Entity12,
          modalLogo: EntitiesImages.E12,
          websiteUrl: 'https://www.mcit.gov.sa/en',
        },
        {
          id: '15',
          name: 'الهيئة السعودية للبيانات والذكاء الاصطناعي',
          info: 'شهد العام 2019 اعتماد استراتيجية سدايا من أجل دعم تحقيق أهداف رؤية المملكة 2030 وإطلاق قدرات المملكة وبهدف بناء اقتصاد قائم على البيانات، فإن الهيئة تعمل على تنظيم قطاع البيانات وتمكين الابتكار والإبداع، وذلك من خلال أذرع ثلاثة هي: مكتب إدارة البيانات الوطنية، ومركز المعلومات الوطني، والمركز الوطني للذكاء الاصطناعي.',
          imageSrc: EntitiesImages.Entity42,
          modalLogo: EntitiesImages.E42,
          websiteUrl: 'https://sdaia.gov.sa/?Lang=en&page=SectionHome#',
        },
        {
          id: '16',
          name: 'هيئة تنظيم المياه والكهرباء',
          info: 'أُنشئت الهيئة بقرار مجلس الوزراء رقم (٢٣٦) في ١٤٢٢/٨/٢٧هـ لتقوم بتنظيم قطاع الكهرباء وتحلية المياه في المملكة، كما أُضيف لها تنظيم تبريد المناطق',
          imageSrc: EntitiesImages.Entity10,
          modalLogo: EntitiesImages.E10,
          websiteUrl: 'https://www.ecra.gov.sa/en-us/Pages/default.aspx',
        },
        {
          id: '17',
          name: 'الهيئة العامة للموانئ',
          info: 'تهدف أن تصبح الهيئة العامة للموانئ اللاعب الرئيس الذي يربط الاقتصاد الوطني بالسوق العالمية، وذلك بتوفير منشآت منتجة وآمنة وسليمة بيئيًّا، وتطوير قوى عاملة وطنية ماهرة ومحفزة قادرة على تحمل مسؤولية الأداء وتحقيق الاستدامة المالية.',
          imageSrc: EntitiesImages.Entity15,
          modalLogo: EntitiesImages.E15,
          websiteUrl: 'https://mawani.gov.sa/en-us/Pages/default.aspx',
        },
        {
          id: '18',
          name: 'الهيئة العامة للتجارة الخارجية',
          info: 'نشأت الهيئة بموجب قرار مجلس الوزراء الموقر رقم (211) وتاريخ 01/01/2019 لغرض تعظيم مكاسب المملكة التجارية والاستثمارية الدولية بما يسهم في تعزيز الاقتصاد الوطني',
          imageSrc: EntitiesImages.Entity44,
          modalLogo: EntitiesImages.E44,
          websiteUrl: 'https://gaft.gov.sa/ar/Pages/default.aspx',
        },
        {
          id: '19',
          name: 'المركز الوطني للتنمية الصناعية',
          info: 'المركز الوطني للتنمية الصناعية هو مؤسسة متخصصة في جذب الاستثمار الصناعي والتنمية الصناعية في قلب تحول القطاع الصناعي في المملكة العربية السعودية ، وإنشاء صناعات جديدة لتنويع الاقتصاد وتلبية طموحات رؤية 2030.',
          imageSrc: EntitiesImages.Entity37,
          modalLogo: EntitiesImages.E37,
          websiteUrl: 'https://www.ic.gov.sa/',
        },
        {
          id: '20',
          name: 'وزارة التعليم',
          info: 'سعيًا لتحسين مخرجات التعليم، وتطوير المناهج، وتقليل الفجوة بين التعليم العام والتعليم العالي، وتحقيقاً للترابط والتناغم والتكامل بينهما بما ينعكس إيجابا على الارتقاء بالمخرجات التعليمية، وبما يتناسب مع متطلبات سوق العمل، وتوحيد الجهود واستثمار الطاقات والكفاءات والقدرات في الوزارتين، صدر أمر خادم الحرمين الشريفين الملك سلمان بن عبدالعزيز في ٩ من ربيع الثاني ١٤٣٦ هـ الموافق ٣٠ يناير ٢٠١٥م بدمج وزارتي التربية والتعليم والتعليم العالي في وزارة واحدة بمسمى (وزارة التعليم).',
          imageSrc: EntitiesImages.Entity33,
          modalLogo: EntitiesImages.E33,
          websiteUrl: 'https://moe.gov.sa/en/pages/default.aspx',
        },
        {
          id: '21',
          name: 'وزارة الموارد البشرية والتنمية الاجتماعية',
          info: '\nأنشئت وزارة الموارد البشرية والتنمية الاجتماعية بموجب المرسوم الملكي الكريم الذي صدر في الشهر الأخير من عام 1380 هـ تحت مسمى وزارة العمل والشؤون الاجتماعية، وقامت الوزارة منذ نشأتها بتنمية المجتمعات المحلية واهتمت بلجان المجتمع ومجالس المحافظات والمراكز والهجر ورعاية الشباب والأسرة والجمعيات التعاونية، وحددت الوزارة أهدافها، وجسدتها بأهداف ثلاثة:\nأولاً: رسم السياسة العامة للشؤون الاجتماعية والعمالية في المملكة ضمن إطار مستوحى من القيم والمبادئ والنظم المرعية في المملكة العربية السعودية.\nثانياً: تخطيط وتنفيذ المشروعات.\nثالثاً: الإسهام في توجيه التطوير الاجتماعي في المملكة توجيها متزنا يهدف إلى رفع وعي المواطنين، وتحسين مستوى معيشتهم وتهيئة مقومات الحياة الكريمة لهم في إطار المحافظة على القيم الروحية والخلقية وتدعيمها لبناء مجتمع ناهض متكامل',
          imageSrc: EntitiesImages.Entity31,
          modalLogo: EntitiesImages.E31,
          websiteUrl: 'https://hrsd.gov.sa/en',
        },
        {
          id: '22',
          name: 'الهيئة الملكية للجبيل وينبع',
          info: '\nارتأت قيادة المملكة العربية السعودية تنويع مصادر الدخل الوطني وتوسيع القاعدة الصناعية وتخفيف الاعتماد على البترول، واتخذت في سبيل ذلك عددا من القرارات التاريخية منها صدور المرسوم الملكي رقم م/75 في 16 رمضان 1395 لتأسيس هيئة ملكية تتولى إنشاء مدينتي الجبيل وينبع الصناعيتين، ومنحها استقلال مالي وإداري.\nوفور تأسيسها انطلقت الهيئة الملكية للجبيل وينبع في رحلة التحدي والإنجاز وفق رؤية طموحة لأن تكون الخيار الأفضل للمستثمرين في صناعة البتروكيماويات والصناعات كثيفة الاستخدام للطاقة والمساهم الرئيس للنمو بالمملكة.',
          imageSrc: EntitiesImages.Entity3,
          modalLogo: EntitiesImages.E3,
          websiteUrl: 'https://www.rcjy.gov.sa/',
        },
        {
          id: '23',
          name: 'الهيئة السعودية للمدن الصناعية ومناطق التقنية (مدن)',
          info: 'منذ تأسيسها عام 2001م، اهتمت "مدن" بتطوير الأراضي الصناعية والبنى التحتية المتكاملة، وها هي اليوم تشرف على 35 مدينة صناعية قائمة وأخرى تحت التطوير في مختلف أنحاء المملكة، بالإضافة إلى إشرافها على المجمعات والمدن الصناعية الخاصة.',
          imageSrc: EntitiesImages.Entity2,
          modalLogo: EntitiesImages.E2,
          websiteUrl: 'https://modon.gov.sa/en/Pages/default.aspx',
        },
        {
          id: '24',
          name: 'هيئة المحتوى المحلي والمشتريات الحكومية',
          info: '\nأنشئت هيئة المحتوى المحلي والمشتريات الحكومية بموجب الأمر الملكي رقم (أ/168) وتاريخ 20/4/1440ه، بهدف تنمية المحتوى المحلي بجميع مكوناته على مستوى الاقتصاد الوطني، والارتقاء بأعمال المشتريات الحكومية ومتابعتها؛ لتحقيق الأهداف التنموية والمالية حسب الرؤى والاستراتيجيات والخطط الوطنية، وفقاً للأنظمة والتنظيمات المعمول بها.\nوتتمثل أهم وظائف الهيئة في صياغة السياسات والأنظمة واللوائح، وتحديد المستهدفات، وقياس الأثر المحقّق من المحتوى المحلي وإعداد التقارير بشأنه، والمشاركة في عملية الشراء الاستراتيجي، وتصميم إجراءات المشتريات الحكومية وتطويرها.',
          imageSrc: EntitiesImages.Entity24,
          modalLogo: EntitiesImages.E24,
          websiteUrl: 'https://lcgpa.gov.sa/ar/Pages/default.aspx',
        },
        {
          id: '25',
          name: 'المركز الوطني للرقابة على الالتزام البيئي',
          info: 'انطلاقا من المحافظة على البيئة وحمايتها وصون مواردها وتحقيق التوازن البيئي اتخذت المملكة قراراً بإنشاء المركز الوطني للرقابة على الالتزام البيئي في عام 2020 ككيان مستقل مالياً وإدارياً يعمل بالتكامل مع باقي مكونات الإطار المؤسسي للمنظومة الوطنية للبيئة على مراقبة التزام كافة الأنشطة التنموية بالأنظمة والمعايير والاشتراطات البيئية المعتمدة، كما يقوم بوضع الضوابط والاشتراطات والأنظمة واللوائح البيئية ومتابعة إنفاذها. \n اهداف المركز \n  1-الارتقاء بالالتزام البيئي عبر الحد من تلوث الأوساط البيئية، ورفع كفاءة الأداء الرقابي والتنظيمي. \n 2 - تعزيز قدرات الاستجابة لحالات الطوارئ البيئية المتعلقة باختصاص المركز بالتنسيق مع الجهات ذات العلاقة. \n  3- رفع مشاركة القطاع الخاص في توفير خدمات التزام بيئي بجودة عالية، وبما يعزز فرص التوطين. \n 4- تشجيع البحث والابتكار في مجالات الرصد والتقييم والتقنيات الصديقة للبيئة بالتعاون مع الجامعات ومراكز الأبحاث المحلية والعالمية \n 5- تعزيز الكفاءات البشرية والإمكانيات الفنية والبنية التحتية للارتقاء بفاعلية المركز',
          imageSrc: EntitiesImages.Entity45,
          modalLogo: EntitiesImages.E45,
          websiteUrl: 'https://ncec.gov.sa/',
        },
        {
          id: '26',
          name: 'المركز السعودي لكفاءة الطاقة',
          info: 'يُعنى المركز بترشيد إنتاج واستهلاك الطاقة، بما يكفل رفع كفاءتها في المملكة، وتوحيد الجهود في هذا المجال، سواء بين الجهات الحكومية أو غير الحكومية.',
          imageSrc: EntitiesImages.Entity28,
          modalLogo: EntitiesImages.E28,
          websiteUrl: 'https://www.seec.gov.sa/en/',
        },
        {
          id: '27',
          name: 'البرنامج الوطني لتطوير قطاع الثروة السمكية',
          info: 'ويهدف البرنامج إلى تحقيق الاستفادة المثلى من الموارد الطبيعية للمملكة في مجال الثروة السمكية، ودعم قطاع الاستزراع المائي لزيادة مساهمته في إجمالي الناتج الوطني، وكذلك تحقيق الاكتفاء الذاتي، وتغطية احتياجات المملكة من الأغذية البحرية، إضافة إلى تنويع مصادر الدخل ودعم الاقتصاد بالمملكة.',
          imageSrc: EntitiesImages.Entity38,
          modalLogo: EntitiesImages.E38,
          websiteUrl: 'https://samaq-sa.com/ar/',
        },
        {
          id: '28',
          name: 'صندوق تنمية الموارد البشرية',
          info: 'أنشئ صندوق تنمية الموارد البشرية بموجب قرار مجلس الوزراء رقم ( 107 ) وتاريخ 29 / 04 / 1421 هـ بهدف دعم جهود تأهيل القوى العاملة الوطنية وتوظيفها في القطاع الخاص والقطاع غير الربحي',
          imageSrc: EntitiesImages.Entity22,
          modalLogo: EntitiesImages.E22,
          websiteUrl: 'https://www.hrdf.org.sa/Home/en',
        },
        {
          id: '29',
          name: 'صندوق الاستثمارات العامة',
          info: 'يعنى صندوق الاستثمارات العامة بدعم إطلاق قطاعات وفرص جديدة تساعد على رسم ملامح مستقبل الاقتصاد العالمي، ودفع عجلة التحول الاقتصادي في المملكة العربية السعودية.',
          imageSrc: EntitiesImages.Entity30,
          modalLogo: EntitiesImages.E30,
          websiteUrl: 'https://www.pif.gov.sa/',
        },
        {
          id: '30',
          name: 'هيئة تنمية الصادرات السعودية',
          info: 'تهدف إلى تنمية صادرات غير نفطية متنوعة لاقتصاد مزدهر ودعم المصدرين لرفع تنافسيتهم وترويج منتجاتهم وخدماتهم للتوسع في الأسواق الدولية وتذليل المعوقات التي قد تحد من ذلك',
          imageSrc: EntitiesImages.Entity23,
          modalLogo: EntitiesImages.E23,
          websiteUrl: 'https://www.saudiexports.sa/en',
        },
        {
          id: '31',
          name: 'الهيئة العامة للطيران المدني',
          info: 'تطوير النقل الجوي وفق أحدث المعايير العالمية، وتعزيز مكانة المملكة عالمياً كجهة مؤثرة في صناعة الطيران المدني الدولي، وتحقيق النمو والاستدامة الاقتصادية، وتطبيق الأنظمة واللوائح والإجراءات الكفيلة بسلامة النقل الجوي',
          imageSrc: EntitiesImages.Entity14,
          modalLogo: EntitiesImages.E14,
          websiteUrl: 'https://gaca.gov.sa/web/ar-sa/page/home',
        },
        {
          id: '32',
          name: 'الهيئة العامة للصناعات العسكرية',
          info: 'تعدّ الهيئة العامة للصناعات العسكرية، والتي تأسست بموجب قرار مجلس الوزراء السعودي الصادر في شهر أغسطس 2017، الجهة المسؤولة عن تنظيم وتمكين وترخيص الصناعات العسكرية في المملكة. حيث تحمل على عاتقها مسؤولية بناء قطاع صناعات عسكرية محلي مستدام ينتج عنه منافع اجتماعية واقتصادية كبرى، ويسهم في تعزيز استقلالية المملكة وجاهزيتها العسكرية وأمنها الوطني.',
          imageSrc: EntitiesImages.Entity26,
          modalLogo: EntitiesImages.E26,
          websiteUrl: 'https://www.gami.gov.sa/',
        },
        {
          id: '33',
          name: 'الهيئة العامة للنقل',
          info: 'الهيئة العامة للنقل هي السُلطة التنظيمية والتشريعية لصناعة النقل السككي والبحري والبري في المملكة العربية السعودية، وذلك عبر ترخيصها لأنشطة النقل السككي والنقل البري والنقل البحري ومراقبتها لجودة الخدمة وسلامتها في هذه الأنشطة الحيويّة، ويقع مقر الهيئة الرئيس في العاصمة الرياض، ولها فروع في كل من منطقة مكة المكرمة والمنطقة الشرقية. وإلى جانب دورها التنظيمي، تعمل الهيئة على تطوير أنشطة النقل السككي والبحري والبري بما يوفر بيئة نقل ذات كفاءة وجودة عالية وبكلفة ملائمة، ترتكز على أحدث التقنيات وتعزز فرص الاستثمار في صناعة النقل بما يحقق أهداف التنمية الاقتصادية والاجتماعية، وبما يحقق رؤية المملكة 2030.',
          imageSrc: EntitiesImages.Entity25,
          modalLogo: EntitiesImages.E25,
          websiteUrl: 'https://tga.gov.sa/en/home',
        },
        {
          id: '34',
          name: 'هيئة المدن والمناطق الاقتصادية',
          info: 'هيئة تعنى بتأسيس مدن ومناطق اقتصادية خاصة مستدامة جاذبة للاستثمار، وقادرة على المنافسة عالمياً من خلال توفير البيئة المناسبة، وتقديم خدمات متكاملة بكفاءة عالية.',
          imageSrc: EntitiesImages.Entity5,
          modalLogo: EntitiesImages.E5,
          websiteUrl: 'https://site.ecza.gov.sa/ar',
        },
        {
          id: '35',
          name: 'الصندوق السعودية للتنمية',
          info: 'الصندوق المعني بتمويل المشاريع الإنمائية في الدول النامية، عن طريق منح القروض، وتقديم منح لتمويل الدراسات والدعم المؤسسي، وتقديم التمويل والضمان للصادرات غير النفطية.',
          imageSrc: EntitiesImages.Entity40,
          modalLogo: EntitiesImages.E40,
          websiteUrl: 'https://www.sfd.gov.sa/',
        },
        {
          id: '36',
          name: 'مدينة الملك عبد العزيز للعلوم والتقنية',
          info: 'تعنى مدينة الملك عبدالعزيز للعلوم والتقنية بإجراء البحوث العلمية التطبيقية، لخدمة التنمية، وتقديم المشورة العلمية على المستوى الوطني، والعمل على تطوير آليات لتحويل مخرجات البحث العلمي والتطوير التقني إلى منتجات صناعية.',
          imageSrc: EntitiesImages.Entity17,
          modalLogo: EntitiesImages.E17,
          websiteUrl: 'https://www.kacst.edu.sa/',
        },
        {
          id: '37',
          name: 'مدينة الملك عبد الله للطاقة الذرية والمتجددة',
          info: 'هي الجهة المعنية بالمساهمة في التنمية المستدامة للمملكة، واقتراح السياسة الوطنية للطاقة الذرية والمتجددة، ووضع الخطة والاستراتيجية اللازمة لتنفيذها.',
          imageSrc: EntitiesImages.Entity18,
          modalLogo: EntitiesImages.E18,
          websiteUrl: 'https://www.energy.gov.sa/ar/pages/default.aspx',
        },
        {
          id: '38',
          name: 'المؤسسة العامة للتدريب التقني والمهني',
          info: 'هي الجهة الحكومية المعنية بالتدريب التقني والمهني في المملكة العربية السعودية منذ عام 1980 م',
          imageSrc: EntitiesImages.Entity11,
          modalLogo: EntitiesImages.E11,
          websiteUrl: 'https://www.tvtc.gov.sa/index-en.html',
        },
        {
          id: '39',
          name: 'المركز السعودي للشراكات الاستراتيجية الدولية',
          info: 'المركز السعودي للشراكات الاستراتيجية الدولية (SCISP) جزء من المنظومة الحكومية، ويتمتع بالشخصية الاعتبارية المستقلة، ويرتبط تنظيميًا بمجلس الشؤون الاقتصادية والتنمية، وقد تأسس وفقًا لقرار مجلس الوزراء رقم (127)، وتاريخ 3 ربيع أول 1439هـ (21 نوفمبر 2017م)؛ لهدف تحقيق الانسجام وتوحيد جميع جهود المملكة في شأن شراكاتها الاستراتيجية الدولية مع دول العالم، بما يُسهم في بناء تلك الشراكات الاستراتيجية، وتطويرها، وتعميقها، وتنسيق برامجها، ومتابعتها مع الجهات المعنية',
          imageSrc: EntitiesImages.Entity32,
          modalLogo: EntitiesImages.E32,
          websiteUrl: 'https://scisp.gov.sa/web/',
        },
        {
          id: '40',
          name: 'المؤسسة العامة للخطوط الحديدية',
          info: 'هي شركة متخصصة للخطوط الحديدية، مملوكة لصندوق الاستثمارات العامة، تأسست الشركة بتاريخ 25 ربيع الثاني 1427هـ (2006)، لتكون مظلة إدارية تدخل تحتها شبكة الخطوط الحديدية السعودية التي تربط شمال المملكة بشرقها ووسطها، وتتولى الشركة مسؤوليات تشغيل شبكة الخطوط الحديدية بجميع مرافقها وإدارتها بالكفاءة اللازمة وَفْق معايير التشغيل الاقتصادية وبحسب المقاييس العالمية في الأداء والسلامة.',
          imageSrc: EntitiesImages.Entity41,
          modalLogo: EntitiesImages.E41,
          websiteUrl: 'https://www.sar.com.sa/ar/',
        },
        {
          id: '41',
          name: 'الشؤون الصحية بالحرس الوطني',
          info: 'توفر الشؤون الصحية لوزارة الحرس الوطني رعاية مثلى لكافة الموظفين وذويهم من المرضى المؤهلين كما توفر فرصاً أكاديمية متميزةً وتجري أبحاثاً حديثةً وتشارك في برامج خدمة المجتمع والصناعة المتعلقة بالمجال الصحي وتهدف الشؤون الصحية لوزارة الحرس الوطني لتكون منشأةً متكاملةً ورائدةً عالمياً تتميز بارتقائها بصحة الفرد والمجتمع.',
          imageSrc: EntitiesImages.Entity39,
          modalLogo: EntitiesImages.E39,
          websiteUrl: 'https://ngha.med.sa/english/Pages/default.aspx',
        },
        {
          id: '42',
          name: 'اتحاد الغرف',
          info: 'تأسس مجلس الغـرف التجارية الصناعية السعودية ومقره الرسمي في مدينة الرياض، بموجب مرسـوم ملكي رقم م/6 وتاريخ 30/4/1400 هـ -مارس 1980م، ليتولى بالمصالح المشتركة للغرف التجارية الصناعية بالمملكة البالغ عددها 28 غرفة، ويعنى بتمثيلها على المستويين المحلي والخارجي، ويعمل على تنمية دور القطاع الخاص في الاقتصاد الوطني. بدأ المجلس أعماله الفعلية بتكوين جهازه التنفيذي ، وهو الأمانة العامة لمجلس الغرف السعودية العام 1401هـ 1981م ، ومنذ ذلك التاريخ وهو يخطو خطوات سريعة نحو تحقيق الأهداف المنوطة به.',
          imageSrc: EntitiesImages.Entity21,
          modalLogo: EntitiesImages.E21,
          websiteUrl: 'https://fsc.org.sa/?lang=en',
        },
        {
          id: '43',
          name: 'المجلس الصحي السعودي',
          info: 'يعنى المجلس الصحي السعودي بالتنسيق والتكامل بين الجهات الصحية المختلفة في المملكة، لتقديم خدمات صحية ذات جودة عالية بطريقة ميسرة ومأمونة، بما يمنع الازدواجية وإهدار الموارد.',
          imageSrc: EntitiesImages.Entity27,
          modalLogo: EntitiesImages.E27,
          websiteUrl: 'https://shc.gov.sa/en/Pages/default.aspx',
        },
        {
          id: '44',
          name: 'وحدة التحول الرقمي',
          info: 'وحدة التحول الرقمي هي مركز امتياز أنشئت عام 2017 بأمر ملكي كجهة مستقلة تعمل على تسريع التحول الرقمي في المملكة وتحقيق أهداف رؤية 2030 من خلال التوجيه الاستراتيجي وتقديم الخبرة والإشراف عبر التعاون المشترك مع القطاعين العام والخاص من أجل الارتقاء بمكانة المملكة لتكون بين مصاف الدول المتطورة رقمياً من خلال تنمية اقتصادية مستدامة تعتمد على تعزيز قيم ومفاهيم الابتكار والاستثمار في المواهب الشابة.',
          imageSrc: EntitiesImages.Entity34,
          modalLogo: EntitiesImages.E34,
          websiteUrl: 'https://ndu.gov.sa/en/',
        },
      ]
    : [
        {
          id: '0',
          name: 'Ministry of Industry and Mineral Resources',
          info: 'The Ministry of Industry and Mineral Resources is a Saudi government body responsible for the industry and mineral resources operations. The Ministry was established on 30 August 2019 after the separation of the Ministry of Energy, Industry and Mineral Resources into the Ministry of Energy and the Ministry of Industry and Mineral Resources. The Ministry aims to diversify the economy of the Kingdom away from the oil',
          imageSrc: EntitiesImages.Entity4,
          modalLogo: EntitiesImages.E4,
          websiteUrl: 'https://mim.gov.sa/',
        },
        {
          id: '1',
          name: 'Ministry of Energy',
          info: 'The Ministry of Energy works on the sustainable development of the integrated oil and gas industry in all its stages to achieve the highest added value to the national economy, discover and exploit the Kingdom’s oil and gas resources and achieve the highest returns from them',
          imageSrc: EntitiesImages.Entity35,
          modalLogo: EntitiesImages.E35,
          websiteUrl: 'https://www.moenergy.gov.sa/en/Pages/default.aspx',
        },
        {
          id: '2',
          name: 'Ministry of Transport',
          info: "The Ministry of Transport is responsible for studying, designing, implementing and maintaining the roads projects outside the cities and the urban areas, along with playing the legislator role to all the transport sectors entities' services within the Kingdom. It is within the Ministry's obligations to implement and maintain ring roads, bridges, mountain roads projects and upgrade the road services like turning single road to double, in all the Kingdom’s regions",
          imageSrc: EntitiesImages.Entity13,
          modalLogo: EntitiesImages.E13,
          websiteUrl: 'https://www.mot.gov.sa/en/Pages/default.aspx',
        },
        {
          id: '3',
          name: 'Saudi Industrial Development Fund',
          info: 'Inspired by a daring vision to blaze a path to success for the industrial sector in Saudi Arabia, the Saudi Industrial Development Fund (SIDF) was founded to play a leading role in effectuating development policies and programs. This vision recognizes SIDF as the primary financial enabler for the industrial transformation in Saudi Arabia',
          imageSrc: EntitiesImages.Entity1,
          modalLogo: EntitiesImages.E1,
          websiteUrl: 'https://www.sidf.gov.sa/en/Pages/Home.aspx',
        },
        {
          id: '4',
          name: 'Ministry of Economy and Planning',
          info: 'The Ministry of Economy and Planning is responsible for economic affairs in the Kingdom of Saudi Arabia with setting development plans in line with the Kingdom’s vision',
          imageSrc: EntitiesImages.Entity7,
          modalLogo: EntitiesImages.E7,
          websiteUrl: 'https://www.mep.gov.sa/en',
        },
        {
          id: '5',
          name: 'Saudi Geological Survey',
          info: 'Aims to provide relevant scientific information and advice to the government and other stakeholders through its high level technical expertise and specialized staff in all fields of the earth sciences and through the use of state-of-the-art technologies and methodologies in order to secure adequate national mineral and water resources, to protect our natural environment, and to help mitigate the detrimental impacts of natural hazards with the end goal of achieving a better life for our people',
          imageSrc: EntitiesImages.Entity6,
          modalLogo: EntitiesImages.E6,
          websiteUrl: 'https://sgs.org.sa/en',
        },
        {
          id: '6',
          name: 'Saudi Standards, Metrology and Quality Org.',
          info: 'Saudi Standards, Metrology and Quality Organization (SASO) seeks to provide consumers with the best services, maintain their health and safety and develop and update Saudi standards and technical regulations continuously in order to protect Saudi markets from counterfeit, low-quality and fraudulent products, in addition to supporting the national economy.',
          imageSrc: EntitiesImages.Entity8,
          modalLogo: EntitiesImages.E8,
          websiteUrl: 'https://www.saso.gov.sa/en/pages/default.aspx',
        },
        {
          id: '7',
          name: 'Zakat, Tax and Customs Authority',
          info: 'General Authority of Customs, motivating economy, global logistics center, trade facilitation, revenue achieving, customer care',
          imageSrc: EntitiesImages.Entity19,
          modalLogo: EntitiesImages.E19,
          websiteUrl: 'https://www.customs.gov.sa/',
        },
        {
          id: '8',
          name: 'Saudi Food and Drug Authority',
          info: 'The Saudi Food and Drug Authority regulates and monitors foods, drugs, medicines, and diagnostic devices imported and locally made with the implementation of compulsory standards, testing them in laboratories and taking care of consumer awareness',
          imageSrc: EntitiesImages.Entity29,
          modalLogo: EntitiesImages.E29,
          websiteUrl: 'https://www.sfda.gov.sa/',
        },
        {
          id: '9',
          name: 'Monshaat',
          info: 'Established in 2016, the objectives of the General Authority for Small and Medium Enterprises “Monshaat” are to organize, support, develop and sponsor the SME sector in accordance with best global practices, to increase the productivity of these enterprises and increase their contribution to the GDP from 20% to 35% by 2030.',
          imageSrc: EntitiesImages.Entity20,
          modalLogo: EntitiesImages.E20,
          websiteUrl: 'https://www.monshaat.gov.sa/en',
        },
        {
          id: '10',
          name: 'Ministry of Environment, Water and Agriculture',
          info: 'Aims to maintain distinguished performance in developing and applying comprehensive policies and effective strategies, as well as promoting services by engaging the private sector and the competent authorities, with a view to achieving prosperity and sustainability of the environment, water and agriculture',
          imageSrc: EntitiesImages.Entity36,
          modalLogo: EntitiesImages.E36,
          websiteUrl: 'https://www.mewa.gov.sa/en/Pages/default.aspx',
        },
        {
          id: '11',
          name: 'Ministry of Municipal and Rural Affairs',
          info: 'The Ministry of Municipal and Rural Affairs is responsible for the urban planning of the Kingdom’s cities, the implications of providing roads and essential equipment. It also enhances cities, develops municipal and rural areas, and manages the required services to maintain the environmental cleanliness and health in the Kingdom',
          imageSrc: EntitiesImages.Entity16,
          modalLogo: EntitiesImages.E16,
          websiteUrl: 'https://momrah.gov.sa/en',
        },
        {
          id: '12',
          name: 'Ministry of Health',
          info: 'The Ministry of Health is committed to fulfilling the mission that it has been honored to carry since its inception, which is based on providing health care at all levels, promoting public health, preventing diseases, setting laws and regulations governing the public and private health sector, and monitoring its performance, with attention to research, academic training and health investment fields',
          imageSrc: EntitiesImages.Entity9,
          modalLogo: EntitiesImages.E9,
          websiteUrl: 'https://www.moh.gov.sa/en/Pages/default.aspx',
        },
        {
          id: '13',
          name: 'Ministry of Defense',
          info: 'The Ministry of Defense is a modern institution that has professional and joint military forces to protect the security of the homeland and its interests from the external threat, while leading and participating in strategic alliances with competence and efficiency',
          imageSrc: EntitiesImages.Entity43,
          modalLogo: EntitiesImages.E43,
          websiteUrl: 'https://mod.gov.sa/en/pages/default.aspx',
        },
        {
          id: '14',
          name: 'Ministry of Communications and Information Technology',
          info: "MCIT Aims to develop Saudi Arabia's ICT capacity and strategically invest to grow its future projects to achieve the Kingdom’s Vision 2030. This serves individuals and communities, meeting the national requirements and keeping pace with global developments to attract more foreign technology investments, thus creating a road-map for the future in innovation and digital economy",
          imageSrc: EntitiesImages.Entity12,
          modalLogo: EntitiesImages.E12,
          websiteUrl: 'https://www.mcit.gov.sa/en',
        },
        {
          id: '15',
          name: 'Saudi Data and Ai Authority',
          info: 'SDAIA’s transformation strategy was approved in 2019. The strategy gives SDAIA a core mandate to drive and own the national data and AI agenda to help achieve Vision 2030’s goals and our Kingdom’s highest potential. To fulfill this mandate, SDAIA – and its sub-entities NDMO, NIC, and NCAI – will deliver on the promise to create a data-driven and AI-supported government and economy.',
          imageSrc: EntitiesImages.Entity42,
          modalLogo: EntitiesImages.E42,
          websiteUrl: 'https://sdaia.gov.sa/?Lang=en&page=SectionHome#',
        },
        {
          id: '16',
          name: 'Water and Electricity Regulatory Authority',
          info: 'Water & Electricity Regulatory Authority(WERA) was established pursuant to Council of Ministers Resolution No.(236) dated 27/8/1422 A.H to regulate the electricity and water desalination sector in Saudi Arabia in addition to district cooling.',
          imageSrc: EntitiesImages.Entity10,
          modalLogo: EntitiesImages.E10,
          websiteUrl: 'https://www.ecra.gov.sa/en-us/Pages/default.aspx',
        },
        {
          id: '17',
          name: 'Saudi Ports Authority',
          info: 'Working to build a solid ground for the status of Saudi Ports Authority as a leader of ports sector which link the national economy with international market and the unstoppable work to develop establishments and working force to reach to the highest standards of efficiency and continuously',
          imageSrc: EntitiesImages.Entity15,
          modalLogo: EntitiesImages.E15,
          websiteUrl: 'https://mawani.gov.sa/en-us/Pages/default.aspx',
        },
        {
          id: '18',
          name: 'Saudi General Authority of Foreign Trade',
          info: "established pursuant to Cabinet Resolution No. (211) dated 01/01/2019 for the purpose of maximizing the Kingdom's international trade and investment gains in a way that contributes to strengthening the national economy.",
          imageSrc: EntitiesImages.Entity44,
          modalLogo: EntitiesImages.E44,
          websiteUrl: 'https://gaft.gov.sa/en/pages/default.aspx',
        },
        {
          id: '19',
          name: 'National Industrial development Center',
          info: "National Industrial development Center is the specialized industrial investment attraction & industrial development organization at the center of the transformation of Saudi Arabia's industrial sector, creating new industries to diversify the economy and meet vision 2030 ambitions",
          imageSrc: EntitiesImages.Entity37,
          modalLogo: EntitiesImages.E37,
          websiteUrl: 'https://www.ic.gov.sa/',
        },
        {
          id: '20',
          name: 'Ministry of Education',
          info: 'In an effort to improve education outcomes, develop curricula, reduce the gap between general education and higher education, and achieve coherence, harmony and integration between them, which will reflect positively on upgrading educational outcomes, in line with the requirements of the labor market, and unify efforts and invest energies, competencies and capabilities in the two ministries, the Custodian of the Two Holy Mosques King Salman bin Abdulaziz issued an order on January 30, 2015, merging the Ministries of Education and Higher Education into one ministry under the name (Ministry of Education)',
          imageSrc: EntitiesImages.Entity33,
          modalLogo: EntitiesImages.E33,
          websiteUrl: 'https://moe.gov.sa/en/pages/default.aspx',
        },
        {
          id: '21',
          name: 'Human Resources and Social Development',
          info: '\nThe Ministry of Labor and Social Development was established under the Royal Decree issued in the last month of 1380H under the name of the Ministry of Labor and Social Affairs. Since its inception, the Ministry has promoted the development of local communities and has taken care of community committees, provincial councils, centers, , And its consolidation with three objectives:\nFirstly: To formulate the general policy for social and labor affairs in the Kingdom within the values, principles and systems of the Kingdom of Saudi Arabia.\nSecondly: project planning and implementation.\nThirdly: To participate in guiding the social development in the Kingdom in a balanced direction aimed to raise the awareness of the citizens, improving their standard of living and creating the elements of a decent life within their spiritual and moral values and supporting them to build an integrated society.',
          imageSrc: EntitiesImages.Entity31,
          modalLogo: EntitiesImages.E31,
          websiteUrl: 'https://hrsd.gov.sa/en',
        },
        {
          id: '22',
          name: 'Royal comission for Jubail & Yanbu (RCJY)',
          info: '\nThe leadership of the Kingdom of Saudi Arabia decided to diversify the sources of national income, expand the industrial base and reduce dependence on oil, and for this purpose it took a number of historic decisions, including the issuance of Royal Decree No. M / 75 on 16 Ramadan 1395 to establish a royal commission to establish the industrial cities of Jubail and Yanbu, and grant it financial independence And administrative\nImmediately after its establishment, the Royal comission for Jubail & Yanbu (RCJY) embarked on a journey of challenge and achievement according to an ambitious vision to be the best option for investors in the petrochemical and energy-intensive industries and the main contributor to growth in the Kingdom',
          imageSrc: EntitiesImages.Entity3,
          modalLogo: EntitiesImages.E3,
          websiteUrl: 'https://www.rcjy.gov.sa/',
        },
        {
          id: '23',
          name: 'The Saudi Authority for Industrial Cities and Technology Zones (MODON)',
          info: 'Since its establishment in 2001, Modon has been undertaking the development and supervision of industrial lands and integrated infrastructure. Today, it oversees 35 existing and under development industrial cities across the Kingdom, in addition to private industrial cities and complexes',
          imageSrc: EntitiesImages.Entity2,
          modalLogo: EntitiesImages.E2,
          websiteUrl: 'https://modon.gov.sa/en/Pages/default.aspx',
        },
        {
          id: '24',
          name: 'Local Content & Government Procurement Authority',
          info: '\nThe Local Content and Government Procurement Authority (LCGPA) was founded to develop all local content aspects for the benefit of the national economy, and improve government procurement operations and monitor them based on the applicable regulations and laws\nIts duties include formulating policies and regulations , identifying key targets, measuring and reporting the impact of local content, participating in the strategic procurement process, designing and refining government procurement procedures',
          imageSrc: EntitiesImages.Entity24,
          modalLogo: EntitiesImages.E24,
          websiteUrl: 'https://lcgpa.gov.sa/ar/Pages/default.aspx',
        },
        {
          id: '25',
          name: 'National Center for Environmental Compliance',
          info: 'In our pursuit to towards protecting our environment and preserving its resources, the Kingdom has taken a decision to establish the National Center for Environmental Compliance in 2020 and to make it financially and administratively independent entity that works in integration with the rest of government entities to monitor the compliance on all approved environmental regulations, standards and requirements. \n Center Objectives: \n 1- Enhancing the environmental compliance by raising the performance efficiency of regulatory authorities. \n 2- Strengthening the capabilities of responding to environmental emergencies in coordination with the relevant authorities. \n 3- Increasing the participation of the private sector in providing high-quality environmental compliance services, in a way that enhances localization opportunities in this segment.',
          imageSrc: EntitiesImages.Entity45,
          modalLogo: EntitiesImages.E45,
          websiteUrl: 'https://ncec.gov.sa/',
        },
        {
          id: '26',
          name: 'Saudi Energy Efficiency Center',
          info: 'The Saudi Energy Efficiency Center concerns with rationalizing the production and consumption of energy in order to increase efficiency in the Kingdom and unifying efforts in this field, whether governmental or non-governmental',
          imageSrc: EntitiesImages.Entity28,
          modalLogo: EntitiesImages.E28,
          websiteUrl: 'https://www.seec.gov.sa/en/',
        },
        {
          id: '27',
          name: 'National Fisheries Development Program',
          info: 'The program aims to achieve optimum utilization of the Kingdom’s natural resources in the field of fisheries, and to support the aquaculture sector to increase its contribution to the gross national product, as well as achieve self-sufficiency and cover the Kingdom’s needs for seafood, in addition to diversifying sources of income and supporting the Kingdom’s economy',
          imageSrc: EntitiesImages.Entity38,
          modalLogo: EntitiesImages.E38,
          websiteUrl: 'https://samaq-sa.com/',
        },
        {
          id: '28',
          name: 'Human Resources Development Fund',
          info: 'The Human Resources Development Fund was established by Cabinet Resolution No. (107) dated 29/04/1421 AH with the aim of supporting efforts to qualify the national workforce and employ them in the private and non-profit sectors.',
          imageSrc: EntitiesImages.Entity22,
          modalLogo: EntitiesImages.E22,
          websiteUrl: 'https://www.hrdf.org.sa/Home/en',
        },
        {
          id: '29',
          name: 'Public Investment Fund',
          info: 'The Public Investment Fund (PIF) supports the launch of new sectors and opportunities that helps in shaping the future of the global economy and drives economic transformation in Saudi Arabia',
          imageSrc: EntitiesImages.Entity30,
          modalLogo: EntitiesImages.E30,
          websiteUrl: 'https://www.pif.gov.sa/',
        },
        {
          id: '30',
          name: 'Saudi Exports Development Authority',
          info: 'Aims to develop diverse non-oil exports for a thriving economy and Support exporters to increase their competitiveness, promote their goods and services to expand internationally, and remove barriers that hinder them',
          imageSrc: EntitiesImages.Entity23,
          modalLogo: EntitiesImages.E23,
          websiteUrl: 'https://www.saudiexports.sa/en',
        },
        {
          id: '31',
          name: 'General Authority of Civil Aviation',
          info: 'Aims to develop the air transport industry in accordance with the latest international standards, strengthen the position of the Kingdom as a globally influential player in civil aviation, achieve financial growth and sustainability, and enforce the relevant rules, regulations and procedures to ensure air transport safety and security',
          imageSrc: EntitiesImages.Entity14,
          modalLogo: EntitiesImages.E14,
          websiteUrl: 'https://gaca.gov.sa/web/en-gb/page/home',
        },
        {
          id: '32',
          name: 'General Authority for Military Industries',
          info: 'Established in accordance with the resolution of the Saudi Council of Ministers in August 2017, the General Authority for Military Industries (GAMI) is the regulator, enabler and licensor of the Kingdom’s defense industry. We are entrusted to build a sustainable domestic defense sector that delivers significant social and economic benefits, while reinforcing the Kingdom’s autonomy, military readiness and national security',
          imageSrc: EntitiesImages.Entity26,
          modalLogo: EntitiesImages.E26,
          websiteUrl: 'https://www.gami.gov.sa/',
        },
        {
          id: '33',
          name: 'Saudi Transport General Authority',
          info: 'TGA organizes, supervises & regulates the public transport industry in the Kingdom of Saudi Arabia, assure proper operations and well management of facilities and equipment, provide service with professional level and appropriate cost, encourage investment in accordance with the economic and social development objectives in the Kingdom, fulfilment of Vision 2030 objectives taking into account the technical and environmental aspects and integration with Air Transport Laws',
          imageSrc: EntitiesImages.Entity25,
          modalLogo: EntitiesImages.E25,
          websiteUrl: 'https://tga.gov.sa/en/home',
        },
        {
          id: '34',
          name: 'Economic Cities and Special Zones Authority',
          info: 'ECZA is concerned with establishing sustainable special economic cities and zones that attract investment, and is able to compete globally by providing the appropriate environment and providing integrated services with high efficiency',
          imageSrc: EntitiesImages.Entity5,
          modalLogo: EntitiesImages.E5,
          websiteUrl: 'https://site.ecza.gov.sa/en',
        },
        {
          id: '35',
          name: 'Saudi Fund for Development',
          info: 'The Saudi Fund for Development provides financing development projects in developing countries by granting loans, funding for studies and institutional support, funding and assuring non-oil exports',
          imageSrc: EntitiesImages.Entity40,
          modalLogo: EntitiesImages.E40,
          websiteUrl: 'https://www.sfd.gov.sa/',
        },
        {
          id: '36',
          name: 'King Abdulaziz City for Science and Technology',
          info: 'King Abdulaziz City for Science and Technology (KACST) applies applied scientific research to serve the development and provide counsel scientific at the national level. It develops mechanisms to transform the outputs of scientific research and technical development into industrial products',
          imageSrc: EntitiesImages.Entity17,
          modalLogo: EntitiesImages.E17,
          websiteUrl: 'https://www.kacst.edu.sa/',
        },
        {
          id: '37',
          name: 'King Abdullah City for Atomic and Renewable Energy',
          info: 'Contributes to the sustainable development of the Kingdom, suggests a national policy for nuclear and renewable energy, and develops the plan and strategy required for the implementation',
          imageSrc: EntitiesImages.Entity18,
          modalLogo: EntitiesImages.E18,
          websiteUrl: 'https://www.energy.gov.sa/ar/pages/default.aspx',
        },
        {
          id: '38',
          name: 'Technical and Vocational Training Corporation',
          info: 'a government agency responsible of regulating and providing technical and vocational training in the kingdom of Saudi Arabia since 1980 AD',
          imageSrc: EntitiesImages.Entity11,
          modalLogo: EntitiesImages.E11,
          websiteUrl: 'https://www.tvtc.gov.sa/index-en.html',
        },
        {
          id: '39',
          name: 'Saudi Center for International Strategic Partners',
          info: 'The Saudi Center for International Strategic Partnerships "SCISP" is a standalone government entity linked to the Council of Economic and Development Affairs, pursuant to the Council of Ministers’ Decision No. 127, dated November 21, 2017; approving the formation of SCISP. SCISP aims to coordinate all the Kingdom’s efforts in relation to its international and regional strategic partnerships with partner countries, in an effort to build, develop and strengthen such partnerships, as well as coordinate and monitor their programs with relevant agencies, through SCISP\'s mandate and assigned tasks in the governmental ecosystem.',
          imageSrc: EntitiesImages.Entity32,
          modalLogo: EntitiesImages.E32,
          websiteUrl: 'https://scisp.gov.sa/web/',
        },
        {
          id: '40',
          name: 'Saudi Arabia Railways',
          info: 'It is a specialized company for railways, owned by the Public Investment Fund, the company was established on Rabi` al-Thani 25, 1427 AH (2006), to be an administrative umbrella under which the Saudi railways network that connects the north of the Kingdom with its east and center, and the company undertakes the responsibilities of operating the railway network with all its facilities and managing it efficiently In accordance with economic operating standards and international standards in performance and safety',
          imageSrc: EntitiesImages.Entity41,
          modalLogo: EntitiesImages.E41,
          websiteUrl: 'https://www.sar.com.sa/',
        },
        {
          id: '41',
          name: 'Ministry of National Guard - Health Affairs',
          info: 'The Ministry of National Guard Health Affairs provides optimal care for all qualified patients and employees and their families, as well as provides excellent academic opportunities, conducts modern research, and participates in community service and industry programs related to the health field',
          imageSrc: EntitiesImages.Entity39,
          modalLogo: EntitiesImages.E39,
          websiteUrl: 'https://ngha.med.sa/english/Pages/default.aspx',
        },
        {
          id: '42',
          name: 'Federation of Saudi Chambers',
          info: 'The Council for Saudi Chambers of Commerce and Industry is the official federation for the 28 Saudi Chambers. The Council was formed as per the Royal Decree # R/6 dated 30/04/1400 Hijri (March 1980) with its head office in Riyadh. Its main objective is to observe the common interests of the Saudi Chambers, represent them on local and international levels and assist in the enhancement of the private sector’s role in the development of the national economy. When the Council formed its executive arm, the General Secretariat of the Council, it started its actual tasks as of 1401 H (1981). Since then, the Council took good strides towards the realization of the objectives assigned to it. The key role of the Council is to serve the common interests of the Saudi Chambers, support the development of the private sector and enhance its role in the national development. The Council managed, through the support of the Chambers and relevant government authorities, to realize a large portion of its objectives in different fields.',
          imageSrc: EntitiesImages.Entity21,
          modalLogo: EntitiesImages.E21,
          websiteUrl: 'https://fsc.org.sa/?lang=en',
        },
        {
          id: '43',
          name: 'Saudi Health Council',
          info: 'The Saudi Health Council coordinates and integrates between the different health agencies in the Kingdom to provide high-quality health services in a conveniently and safely, therefore preventing duplication and waste of resources',
          imageSrc: EntitiesImages.Entity27,
          modalLogo: EntitiesImages.E27,
          websiteUrl: 'https://shc.gov.sa/en/Pages/default.aspx',
        },
        {
          id: '44',
          name: 'National Digital Transformation Unit',
          info: "The National Digital Transformation Unit, which was founded as an independent agency in 2017 pursuant to a royal decree, is a center of excellence mandated to accelerate digital transformation in the Kingdom and to work toward achieving the objectives of Vision 2030. The Vision's objectives are to be realized through strategic guidance and providing expertise and supervision by cooperating with the public and private sectors to place the Kingdom among the world's digitally developed nations. The National Digital Transformation Unit aims at achieving sustainable economic development that is based on promoting innovation and investing in young talents",
          imageSrc: EntitiesImages.Entity34,
          modalLogo: EntitiesImages.E34,
          websiteUrl: 'https://ndu.gov.sa/en/',
        },
      ];
};
