export enum Route {
  EXPLORE = 'explore',
  PROFILE = 'profile',
  LOGIN = 'login',
  REGISTER = 'register',
  TAB_NAV = 'tabNav',
  NEWS = 'news',
  ARCHIVE = 'archive',
  SECTORS_PARENT = 'sectorsParent',
  SECTORS = 'sectors',
  SPECHIAL_ENABLERS = 'sperchialEnablers',
  GENERAL_ENABLERS = 'generalEnablers',
  ABOUT_DALEEL = 'aboutDaleel',
  ONBOARDING = 'onBoarding',
  HELP = 'help',
  MARKET_INSIGHTS = 'MarketInsights',
  MARKET_INSIGHTS_FIELD = 'MarketInsightsField',
  INDUSTRIAL_MAP = 'IndustrialMap',
  EXPLORE_NAV_TAB = 'exploreNavTab',
  ENABLERS = 'enablers',
  Notifications = 'Notifications',
}
